STEP_ADDED = 0
STEP_CLONING = 1
STEP_CLONED = 2
STEP_SEMGREPING = 3
STEP_SEMGREPED = 4
STEP_POC_SUCCESS = 5
STEP_POC_CVSS_READY = 6
STEP_PATCH_READY = 7
STEP_PATCH_SENT = 8

PAUSED_HTTP_CLONE_FAILED = 0
PAUSED_CLONE_FS_SAVE_FAILED = 1

PAUSED_SEMGREP_FAILED = 2
PAUSED_SEMGREP_NO_RESULT = 3
PAUSED_SEMGREP_UNKNOWN_ERROR = 4
PAUSED_INVALID_FILE_FORMAT = 40
PAUSED_POC_START_FAILED = 5
PAUSED_POC_NO_OPEN_PORTS = 6
PAUSED_POC_NOT_VULNERABLE_NETWORK = 7
PAUSED_POC_NOT_VULNERABLE_LOCAL = 8

PAUSED_PATCH_FAILED = 10
PAUSED_UNKNOWN_REASON_ISSUE = 11
PAUSED_UNKNOWN_REASON_ISSUE2 = 12
PAUSED_PROJECT_WAS_FIXED = 13

PAUSED_UNKNOWN_ERROR_AFTER_PATCHING = 14
PAUSED_UNKNOWN_ERROR_GHAPI = 15
PAUSED_UNKNOWN_ERROR_EXCEPTION = 16
PAUSED_VULN_IS_PATCHED = 17
PAUSED_VULN_ALREADY_REPORTER = 18
PAUSED_PROJECT_IS_BUGGY = 19
PAUSED_PROJECT_IS_BUGGY = 20
PAUSED_PROJECT_NOT_VULNERABLE_ANYMORE = 21
PAUSED_PATCHING_FAILED = 22
PAUSED_VULNERABLE_CODE_DELETED = 30

DOS_NOT_CHECKED = 0
DOS_VULNERABLE = 1
DOS_NOT_VULNERABLE = 2
